#! /bin/bash

echo "Bash version ${BASH_VERSION}..."


conda update conda mamba -y -n base

for env in $(conda env list | cut -d" " -f1 | tail -n+4)
do 
    echo      
    echo      
    echo      
    echo  "*******************************************************************"
    echo  $env $env $env $env $env $env $env $env
    echo  "*******************************************************************"
    mamba update --all -y -n $env
    mamba env export -n $env > ~/Admin/Anaconda/$env.yml
    mamba list -n $env > ~/Admin/Anaconda/$env.txt
done

cp -v ~/Admin/Anaconda/EM39.* ~/AEMpyX/environment/linux/
cp -v ~/Admin/Anaconda/EM39.* ~/Py4MT/environment/

cp -v ~/Admin/Anaconda/base.* ~/AEMpyX/environment/linux/
cp -v ~/Admin/Anaconda/base.* ~/Py4MT/environment/

cp -v ~/Admin/Anaconda/AEMpyX.* ~/AEMpyX/environment/linux/

