#! /bin/bash

export MY_CONDA_ROOT=${HOME}/.Miniconda24/
export AEMPYX_ROOT=${HOME}/AEMpyX_public/
export AEMPYX_DATA=${HOME}/AEMpyX_public/work/


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$('/home/vrath/.Miniconda/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
__conda_setup="$('${MY_CONDA_ROOT}/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f ${MY_CONDA_ROOT}/etc/profile.d/conda.sh ]; then
        . ${MY_CONDA_ROOT}/etc/profile.d/conda.sh
    else
        export PATH='${MY_CONDA_ROOT}/bin:$PATH'
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

conda activate AEM
cd ${AEMPYX_ROOT}
