#! /bin/bash
export MY_ROOT=$HOME
export CONDA_ROOT=${HOME}/.Miniconda2024/

echo "Bash version ${BASH_VERSION}..."
. /home/vrath/bin/conda_init
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$('/home/vrath/.Miniconda/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
__conda_setup="$('${MY_CONDA_ROOT}/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f ${MY_CONDA_ROOT}/etc/profile.d/conda.sh ]; then
        . ${MY_CONDA_ROOT}/etc/profile.d/conda.sh
    else
        export PATH='${MY_CONDA_ROOT}/bin:$PATH'
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

conda update --all -y  -n base

for env in $(conda env list | cut -d" " -f1 | tail -n+4)
do 
    echo      
    echo      
    echo      
    echo  "*******************************************************************"
    echo  $env $env $env
    echo  "*******************************************************************"
    conda update --all -y -n $env
    conda env export -n $env > ~/Admin/CondaAdmin/$env.yml
    conda list -n $env > ~/Admin/CondaAdmin/$env.txt
done

# cp -v ~/Admin/CondaAdmin/base.* ~/AEMpyX/environment/linux/ubuntu22.04/
# cp -v ~/Admin/CondaAdmin/base.* ~/Py4MT/environment/
# cp -v ~/Admin/CondaAdmin/base.* ~/JacoPyAn/environment/
#
# cp -v ~/Admin/CondaAdmin/JacoPyAn8.* ~/JacoPyAn/environment/
# cp -v ~/Admin/CondaAdmin/AEMpyX*.* ~/AEMpyX/environment/linux/ubuntu22.04/
# cp -v ~/Admin/CondaAdmin/Py4MT*.* ~/AEMpyX/environment/linux/ubuntu22.04/

