#! /bin/bash

echo "Bash version ${BASH_VERSION}..."


conda update conda mamba -y -n base

for env in $(conda env list | cut -d" " -f1 | tail -n+4)
do 
    echo      
    echo      
    echo      
    echo  "*******************************************************************"
    echo  $env $env $env $env $env $env $env $env
    echo  "*******************************************************************"
#     mamba update --all -y -n $env
    mamba env export -n $env > ~/Admin/anaconda/$env.yml
    mamba list -n $env > ~/Admin/anaconda/$env.txt
done

# cp -v ~/Admin/anaconda/EM39.* ~/AEMpyX/environment/linux/
# cp -v ~/Admin/anaconda/EM39.* ~/Py4MT/environment/
#
# cp -v ~/Admin/anaconda/base.* ~/AEMpyX/environment/linux/
# cp -v ~/Admin/anaconda/base.* ~/Py4MT/environment/
#
# cp -v ~/Admin/anaconda/AEMpyX.* ~/AEMpyX/environment/linux/

